### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by fedebotu** [fedebotu/kaist-safety-course-bot#2]
It would be very useful to have the app translated in Korean!
Will be grateful if you would like to help :)

**Comment by SNP0301** [comment]
Hi, I think I can translate it into Korean!
Is there any specific guideline or step that I have to follow?

**Comment by fedebotu** [comment]
Hi @SNP0301 ! 
Since I am not an actual app developer, I don't really know how to handle translations... 
Here are some to-dos and recommendations:

### Tasks
- [ ] Translate [GUI](https://github.com/fedebotu/kaist-safety-course-bot/tree/main/kaist/gui)
- [ ] Translate debugger printing messages (normal `print` functions)
- [ ] Translate README (possible solution [here](https://github.com/jonatasemidio/multilanguage-readme-pattern))

### Recommendations
In general, for our case, I would say the simplest way would be to set the language as a configuration option and then call the text dynamically depending on the config (similar to what they do [here](https://stackoverflow.com/questions/42044082/tkinter-and-multilanguage)). A more powerful way would be to use the [gettext](https://docs.python.org/3/library/gettext.html) module, but this might be overkill.
___

Anyways, you are pretty much free to do it your way, it would be great if you can contribute :)

**Comment by fedebotu** [comment]
Exactly! 
(in that case it should be e.g. 0 for ENG and 1 for KOR, just a minor comment about indexing :) )

**Comment by fedebotu** [comment]
## Update
README translation done with #6  , kudos to @SNP0301 !
